services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        VITE_SERVER_URL: ${VITE_SERVER_URL}
        VITE_SERVER_URL_INTERNAL: ${VITE_SERVER_URL_INTERNAL}
    depends_on:
      - server
    environment:
      VITE_SERVER_URL: ${VITE_SERVER_URL}
      VITE_SERVER_URL_INTERNAL: ${VITE_SERVER_URL_INTERNAL}

  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_BUCKET: ${S3_BUCKET}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_REGION: ${S3_REGION}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      CORS_ORIGIN: ${CORS_ORIGIN}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL}
      MAIN_ADMIN_EMAIL: ${MAIN_ADMIN_EMAIL} 
      MAIN_ADMIN_PASSWORD: ${MAIN_ADMIN_PASSWORD}
#
# version: "3"
#
# services:
#   redis:
#     image: "redis:latest"
#     ports:
#       - "6379:6379"
#     environment:
#       - REDIS_PASSWORD=password
#       - REDIS_USER=w1png
#       - REDIS_USER_PASSWORD=password
#
#   minio:
#       image: "minio/minio:latest"
#       ports:
#         - "9000:9000"
#         - "9090:9090"
#       environment:
#         MINIO_ROOT_USER: "root"
#         MINIO_ROOT_PASSWORD: "12345678"
#       volumes:
#         - "minio:/data/minio"
#       command: minio server /data/minio --console-address ":9090"
#       restart: 
#         always
# volumes:
#   minio:
